import javax.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vaibhav
 */
public class PRO_DETAILS extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    /**
     * Creates new form PRO_DETAILS
     */
    public PRO_DETAILS() {
        initComponents();
         
        try{
            Class.forName("java.sql.Driver");

            Connection Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
            stmt=Con.createStatement();
            String query= "select * from product";
            rs=stmt.executeQuery(query);
            rs.next();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("SNO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, -1));

        T1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, -1));

        jLabel7.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("              PRODUCT DETAILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 590, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 150, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 150, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 150, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 150, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 150, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 150, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton10.setText("LAST");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 160, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton9.setText("PREVIOUS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton8.setText("NEXT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 160, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton7.setText("FIRST");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("PRICE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 90, -1));

        T6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 150, -1));

        T5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 150, -1));

        T4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, -1));

        T3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 150, -1));

        T2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("SIZE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("COLOUR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("QUANTITY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t5.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int cno;
    cno=Integer.parseInt(T1.getText());
    try{
             Class.forName("java.sql.DriverManager");
             Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
             Statement stmt=(Statement)Con.createStatement();
             String query= "select * from product where CNO="+cno;
              ResultSet rs=stmt.executeQuery(query);
            if(rs.next()){
             T2.setText(rs.getString("name"));
             T3.setText(rs.getString("size"));
             T4.setText(rs.getString("colour"));
             T5.setText(rs.getString("quantity"));
             T6.setText(rs.getString("price"));
             jButton1.setEnabled(false);
             jButton4.setEnabled(true);
             jButton3.setEnabled(true);
             jButton2.setEnabled(false);
            }       
             
            else{
           JOptionPane.showMessageDialog(null,"NOT FOUND");
           T1.setText("");           
           T1.requestFocus();
            }
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int cno,s=0,q=0,p=0,rs;
    String n=T2.getText(),c=T4.getText();
    cno=Integer.parseInt(T1.getText());
    s=Integer.parseInt(T3.getText());
    q=Integer.parseInt(T5.getText());
    p=Integer.parseInt(T6.getText());
    try{
             Class.forName("java.sql.DriverManager");
             Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
             Statement stmt=(Statement)Con.createStatement();
             String query= "insert into product values('"+n+"','"+s+"','"+c+"',"+q+","+p+","+cno+")";
             rs=stmt.executeUpdate(query);
          if(rs>0){
             JOptionPane.showMessageDialog(null,"INSERTED");
           T1.setText("");
           T2.setText("");
           T3.setText("");
           T4.setText("");
           T5.setText("");
           T6.setText("");
           T1.requestFocus();
            }       
             
          else{
           JOptionPane.showMessageDialog(null,"ERROR");
           T1.setText("");
           T2.setText("");
           T3.setText("");
           T4.setText("");
           T5.setText("");
           T6.setText("");
           T1.requestFocus();
            }
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int cno;
    cno=Integer.parseInt(T1.getText());
    try{
             Class.forName("java.sql.DriverManager");
             Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
             Statement stmt=(Statement)Con.createStatement();
             String query= "delete from product where CNO="+cno;
            int rs=stmt.executeUpdate(query);
            if(rs>0){
             JOptionPane.showMessageDialog(null,"DELETED");
             jButton1.setEnabled(true);
             jButton2.setEnabled(true);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             T1.setText("");
             T2.setText("");
             T3.setText("");
             T4.setText("");
             T5.setText("");
             T6.setText("");
             T1.requestFocus();
            }       
             
            else{
           JOptionPane.showMessageDialog(null,"NOT FOUND");
           T1.setText("");           
           T1.requestFocus();
            }
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int cno,s=0,q=0,p=0,rs;
    String n=T2.getText(),c=T4.getText();
    cno=Integer.parseInt(T1.getText());
    s=Integer.parseInt(T3.getText());
    q=Integer.parseInt(T5.getText());
    p=Integer.parseInt(T6.getText());
    try{
             Class.forName("java.sql.DriverManager");
             Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
             Statement stmt=(Statement)Con.createStatement();
             String query="update product set name='"+n+"',size='"+s+"',colour='"+c+"',quantity="+q+",price="+p+" where cno="+cno;
             rs=stmt.executeUpdate(query);
          if(rs>0){
             JOptionPane.showMessageDialog(null,"UPDATED");
             jButton1.setEnabled(true);
             jButton2.setEnabled(true);
             jButton3.setEnabled(false);
             jButton4.setEnabled(false);
             T1.setText("");
           T2.setText("");
           T3.setText("");
           T4.setText("");
           T5.setText("");
           T6.setText("");
           T1.requestFocus();
            }       
             
          else{
           JOptionPane.showMessageDialog(null,"ERROR");
           T1.setText("");
           T2.setText("");
           T3.setText("");
           T4.setText("");
           T5.setText("");
           T6.setText("");
           T1.requestFocus();
            }
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    T1.setText("");
    T2.setText("");
    T3.setText("");
    T4.setText("");
    T5.setText("");
    T6.setText("");
    T1.requestFocus();
    jButton1.setEnabled(true);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    MENU fr=new MENU();
    fr.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try{
            rs.first();
            T1.setText(rs.getInt("cno")+"");
            T2.setText(rs.getString("name"));
            T3.setText(rs.getString("size"));
            T4.setText(rs.getString("colour"));
            T5.setText(rs.getString("quantity"));
            T6.setText(rs.getString("price"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            rs.next();
            if(rs.isBeforeFirst()){
                rs.previous();
            }
            T1.setText(rs.getInt("cno")+"");
            T2.setText(rs.getString("name"));
            T3.setText(rs.getString("size"));
            T4.setText(rs.getString("colour"));
            T5.setText(rs.getString("quantity"));
            T6.setText(rs.getString("price"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{

            rs.previous();
            T1.setText(rs.getInt("cno")+"");
            T2.setText(rs.getString("name"));
            T3.setText(rs.getString("size"));
            T4.setText(rs.getString("colour"));
            T5.setText(rs.getString("quantity"));
            T6.setText(rs.getString("price"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
            rs.last();
            T1.setText(rs.getInt("cno")+"");
            T2.setText(rs.getString("name"));
            T3.setText(rs.getString("size"));
            T4.setText(rs.getString("colour"));
            T5.setText(rs.getString("quantity"));
            T6.setText(rs.getString("price"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRO_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRO_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRO_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRO_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRO_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
