import java.sql.*;
import javax.swing.JOptionPane;
public class SALE extends javax.swing.JFrame {

    /**
     * Creates new form SALE
     */
    public SALE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        co1 = new javax.swing.JComboBox<>();
        priceRS = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        T4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        R2 = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("QUANTITY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        T1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T1.setText("0");
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 170, -1));

        co1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        co1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co1ActionPerformed(evt);
            }
        });
        getContentPane().add(co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 170, -1));

        priceRS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceRS.setForeground(new java.awt.Color(204, 255, 204));
        getContentPane().add(priceRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("per pcs.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 170, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("SAVE");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 170, -1));

        T2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T2.setText("0");
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 170, -1));

        T3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T3.setText("0");
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 170, -1));

        T4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T4.setText("0");
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 170, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 100, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("NET AMOUNT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("DISCOUNT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("GROSS AMOUNT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        R2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R2.setForeground(new java.awt.Color(204, 255, 204));
        R2.setText("CREDIT");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        R1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R1.setForeground(new java.awt.Color(204, 255, 204));
        R1.setText("CASH");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("PRICE (in RS)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("PRODUCT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        jLabel10.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("                    SALES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 470, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void co1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co1ActionPerformed
        // TODO add your handling code here:
        int a;
        double qt,p=0;
        String n=null,f=null;
        for(a=0;a<=co1.getItemCount();a++){
            if(co1.getSelectedIndex()==a){
                n=co1.getItemAt(a);
            }
        }
        try{
            Class.forName("java.sql.DriverManager");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
            Statement stmt=(Statement)Con.createStatement();
            String query= "select * from product where name='"+n+"'";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                f=rs.getString("quantity");
                qt=Integer.parseInt(f);
                f=rs.getString("price");
                p=Integer.parseInt(f)+(Integer.parseInt(f)*10/100);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        priceRS.setText(""+p);  
    }//GEN-LAST:event_co1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed

    }//GEN-LAST:event_R2ActionPerformed
int na=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int a;
        double q,p=0,g,d=0,qt=0;
        String n=null,f=null;
        for(a=0;a<=co1.getItemCount();a++){
            if(co1.getSelectedIndex()==a){
                n=co1.getItemAt(a);
            }
        }
        q=Integer.parseInt(T1.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
            Statement stmt=(Statement)Con.createStatement();
            String query= "select * from product where name='"+n+"'";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                f=rs.getString("quantity");
                qt=Integer.parseInt(f);
                f=rs.getString("price");
                p=Integer.parseInt(f)+(Integer.parseInt(f)*10/100);
            }
            if(q<=qt){
                jButton1.setEnabled(false);
                jButton4.setEnabled(true);
                if(R1.isSelected()){
                    d=(q*p)*.05;
                }
                else if(R2.isSelected()){
                    d=0;
                }
                na=(int) ((q*p)-d);
                T2.setText(""+(q*p));
                T3.setText(""+d);
                T4.setText(""+na);
            }
            else{
                JOptionPane.showMessageDialog(null,"quantity unavailable");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton1.setEnabled(true);
        jButton4.setEnabled(false);
        int q=Integer.parseInt(T1.getText()),a;
        String n=null;
        for(a=0;a<=co1.getItemCount();a++){
            if(co1.getSelectedIndex()==a){
                n=co1.getItemAt(a);
            }
        }

        try{
            Class.forName("java.sql.DriverManager");
            Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
            Statement stmt=(Statement)Con.createStatement();
            String query= "update product set quantity=quantity-"+q+" where name='"+n+"'";
            stmt.executeUpdate(query);

            JOptionPane.showMessageDialog(null,"SAVED");

            if(R2.isSelected()){
                CREDIT_SALE fr=new CREDIT_SALE(na);
                fr.setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    BILL fr= new BILL();
    fr.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        T1.setText("");
        T2.setText("");
        T3.setText("");
        T4.setText("");
        R1.setSelected(true);
        R2.setSelected(false);
        T1.requestFocus();
        jButton4.setEnabled(false);
        jButton1.setEnabled(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        R1.setSelected(true);
        try{
             Class.forName("java.sql.DriverManager");
             Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vd","root","123456");
             Statement stmt=(Statement)Con.createStatement();
             String query= "select name from product";
              ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
             
             co1.addItem(rs.getString("name"));
            }       
             
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
    }//GEN-LAST:event_formWindowOpened

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SALE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> co1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel priceRS;
    // End of variables declaration//GEN-END:variables
}
